Misc. improvements

diff --git a/src/bell/program b/src/bell/program
--- a/src/bell/program
+++ b/src/bell/program
@@ -10,21 +10,28 @@ fi
 
 while [ true ]
 do
-        echo -e "\n\033[1;33mProgramming\033[0m\n"
-        espeak "Programming"
+	make read > /dev/null 2> /dev/null
+
+	while [ $? -ne 0 ]
+	do
+		echo -n .
+		make read > /dev/null 2> /dev/null
+	done
+
+	echo -e "\n\033[1;33mProgramming\033[0m\n"
+	espeak "Programming"
 	make fuse
 	make firmware HEX=$1
 
 	if [ $? -eq 0 ]
-        then 
-                echo -e "\033[0;32mComplete\033[0m\n"
-                espeak "Complete"
-        else 
-                echo -e "\033[0;31mFailed\033[0m\n"
-                espeak "Failed"
- 	fi
+	then 
+		echo -e "\033[0;32mComplete\033[0m\n"
+		espeak "Complete"
+	else 
+		echo -e "\033[0;31mFailed\033[0m\n"
+		espeak "Failed"
+	fi
+	
+	sleep 1
 
-        read -t 0.1 -n 1000 discard
-        read -n 1 -p "Press any key to continue..."
-        echo
 done
