Added continuous loop

diff --git a/src/bell/program b/src/bell/program
--- a/src/bell/program
+++ b/src/bell/program
@@ -7,11 +7,24 @@ then
 	exit 1
 fi 
 
-espeak "Programming"
-make fuse
-make firmware HEX=$1
 
-if [ $? -eq 0 ]
-then espeak "Complete"
-else espeak "Failed"
-fi
+while [ true ]
+do
+        echo -e "\n\033[1;33mProgramming\033[0m\n"
+        espeak "Programming"
+	make fuse
+	make firmware HEX=$1
+
+	if [ $? -eq 0 ]
+        then 
+                echo -e "\033[0;32mComplete\033[0m\n"
+                espeak "Complete"
+        else 
+                echo -e "\033[0;31mFailed\033[0m\n"
+                espeak "Failed"
+ 	fi
+
+        read -t 0.1 -n 1000 discard
+        read -n 1 -p "Press any key to continue..."
+        echo
+done
